services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      # - /run/dbus:/run/dbus:ro
    ports:
      - 8123:8123
    restart: unless-stopped
    privileged: true
    # network_mode: host
    # environment:
    #   - TZ=Europe/Rome
    #   - PUID=1000
    #   - PGID=1000
    #   - UMASK=022
    #   - HOMEASSISTANT_SERVER_PORT=8123
    #   - HOMEASSISTANT_SERVER_HOST=0.0.0.0
    #   - HOMEASSISTANT_SERVER_SSL=false
    #   - HOMEASSISTANT_SERVER_SSL_CERTIFICATE=/config/ssl/fullchain.pem
    #   - HOMEASSISTANT_SERVER_SSL_KEY=/config/ssl/privkey.pem